// Package planner provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package planner

// List defines model for List.
type List struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	OwnerId     string `json:"owner_id"`
}

// ListIdResponse defines model for ListIdResponse.
type ListIdResponse struct {
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// ListsResponse defines model for ListsResponse.
type ListsResponse struct {
	Lists  []List `json:"lists"`
	Status Status `json:"status"`
}

// NewListRequest defines model for NewListRequest.
type NewListRequest struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// NewTaskRequest defines model for NewTaskRequest.
type NewTaskRequest struct {
	Description string  `json:"description"`
	ListId      *string `json:"listId,omitempty"`
	Name        string  `json:"name"`
}

// Status defines model for Status.
type Status struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	ListId      string `json:"list_id"`
	Name        string `json:"name"`
	OwnerId     string `json:"owner_id"`
	Status      bool   `json:"status"`
}

// TaskIdResponse defines model for TaskIdResponse.
type TaskIdResponse struct {
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	Status Status `json:"status"`
	Tasks  []Task `json:"tasks"`
}

// UpdateListRequest defines model for UpdateListRequest.
type UpdateListRequest struct {
	Description *string `json:"description,omitempty"`
	ListId      *string `json:"listId,omitempty"`
	Name        *string `json:"name,omitempty"`
	Status      *bool   `json:"status,omitempty"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description *string `json:"description,omitempty"`
	ListId      *string `json:"listId,omitempty"`
	Name        *string `json:"name,omitempty"`
	Status      *bool   `json:"status,omitempty"`
}

// GetTasksParams defines parameters for GetTasks.
type GetTasksParams struct {
	// ListId get tasks from list
	ListId *string `form:"listId,omitempty" json:"listId,omitempty"`
}

// CreateListJSONRequestBody defines body for CreateList for application/json ContentType.
type CreateListJSONRequestBody = NewListRequest

// UpdateListJSONRequestBody defines body for UpdateList for application/json ContentType.
type UpdateListJSONRequestBody = UpdateListRequest

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = NewTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest
