// Package planner provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package planner

// NewTaskRequest defines model for NewTaskRequest.
type NewTaskRequest struct {
	Description string `json:"description"`
	Name        string `json:"name"`
}

// Status defines model for Status.
type Status struct {
	Code    int    `json:"code"`
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	Description string `json:"description"`
	Id          string `json:"id"`
	Name        string `json:"name"`
	OwnerId     string `json:"owner_id"`
	Status      bool   `json:"status"`
}

// TaskIdResponse defines model for TaskIdResponse.
type TaskIdResponse struct {
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	Status Status `json:"status"`
	Tasks  []Task `json:"tasks"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	Description *string `json:"description,omitempty"`
	Name        *string `json:"name,omitempty"`
	Status      *bool   `json:"status,omitempty"`
}

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = NewTaskRequest

// UpdateTaskJSONRequestBody defines body for UpdateTask for application/json ContentType.
type UpdateTaskJSONRequestBody = UpdateTaskRequest
