openapi: 3.0.0
info:
  title: Task API
  description: API for task management
  version: 1.0.0
paths:
  /planner/tasks:
    post:
      operationId: createTask
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTaskRequest'
      responses:
        '201':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskIdResponse'
        default:
          description: default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    get:
      operationId: getTasks
      summary: Get all tasks
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TasksResponse'
        default:
          description: default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  '/planner/tasks/{id}':
    patch:
      operationId: updateTask
      summary: Update task parameters
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TasksResponse'
        default:
          description: default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    delete:
      operationId: deleteTask
      summary: Delete task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TasksResponse'
        default:
          description: default
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    UpdateTaskRequest:
      properties:
        status:
          type: boolean
        name:
          type: string
        description:
          type: string
    Task:
      required:
        - id
        - name
        - description
        - status
        - owner_id
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        owner_id:
          type: string
        status:
          type: boolean
    TasksResponse:
      required:
        - status
        - tasks
      properties:
        tasks:
          type: array
          items:
            $ref: '#/components/schemas/Task'
        status:
          $ref: '#/components/schemas/Status'
    TaskIdResponse:
      required:
        - id
        - status
      properties:
        id:
          type: string
        status:
          $ref: '#/components/schemas/Status'
    NewTaskRequest:
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string
    Status:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int
        message:
          type: string
