openapi: 3.0.0
info:
  title: Task API
  description: API for task management
  version: 1.0.0
paths:
  /tasks:
    post:
      operationId: createTask
      summary: Create a new task
      description: Creates a new task with the specified parameters.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTaskRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskIdResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    get:
      operationId: getTasks
      summary: Get all tasks
      description: Gets all actor tasks
      responses:
        '200':
          description: Tasks received
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TasksResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
components:
  schemas:
    Task:
        required:
        - id
        - name
        - description
        - status
        - owner_id
        properties:
          id:
            type: string
            description: Unique id of the task
            example: "550e8400-e29b-41d4-a716-446655440002"
          name:
            type: string
            description: Task name
            example: "Complete the project"
          description:
            type: string
            description: Task description
            example: "The project must be completed by the end of the week."
          owner_id:
            type: string
            description: ID of the task owner
            example: "550e8400-e29b-41d4-a716-446655440000"
          status:
            type: boolean
            description: task status
            example: true
    TasksResponse:
        required:
          - status
          - tasks
        properties:
          tasks:
            type: array
            items:
              $ref: '#/components/schemas/Task'
          status:
            $ref: '#/components/schemas/Status'
    TaskIdResponse:
      required:
        - id
        - status
      properties:
        id:
          type: string
          description: Unique id of the task
          example: "550e8400-e29b-41d4-a716-446655440002"
        status:
          $ref: '#/components/schemas/Status'
    NewTaskRequest:
      required:
        - name
      properties:
        name:
          type: string
          description: Task name
          example: "Complete the project"
        description:
          type: string
          description: Task description
          example: "The project must be completed by the end of the week."
    Status:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int64
          description: Error code
          example: 200
        message:
          type: string
          description: Error message
          example: OK
