// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package handlers

// NewTaskRequest defines model for NewTaskRequest.
type NewTaskRequest struct {
	// Description Task description
	Description *string `json:"description,omitempty"`

	// Name Task name
	Name string `json:"name"`
}

// Status defines model for Status.
type Status struct {
	// Code Error code
	Code int64 `json:"code"`

	// Message Error message
	Message string `json:"message"`
}

// Task defines model for Task.
type Task struct {
	// Description Task description
	Description string `json:"description"`

	// Id Unique id of the task
	Id string `json:"id"`

	// Name Task name
	Name string `json:"name"`

	// OwnerId ID of the task owner
	OwnerId string `json:"owner_id"`

	// Status task status
	Status bool `json:"status"`
}

// TaskIdResponse defines model for TaskIdResponse.
type TaskIdResponse struct {
	// Id Unique id of the task
	Id     string `json:"id"`
	Status Status `json:"status"`
}

// TasksResponse defines model for TasksResponse.
type TasksResponse struct {
	Status Status `json:"status"`
	Tasks  []Task `json:"tasks"`
}

// CreateTaskJSONRequestBody defines body for CreateTask for application/json ContentType.
type CreateTaskJSONRequestBody = NewTaskRequest
